### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by zalokhan** [zalokhan/BookTurks#30]
Add forgot your password field

**Comment by shubham90** [comment]
Things to do:
- Create a view for inputting the username and verifying
- Send email with a unique link for resetting the password
- create a view for updating password
- Verify the email link is valid for the current user
- Update the password in db

**Comment by zalokhan** [comment]
Instead of a completely new view, we can append to the same page with a small popup modal. This will keep the user on the same page and make it quicker.
Rest looks good to me.

**Comment by zalokhan** [comment]
#35
